### ISSUE TITLE
Crash during: dotnet new <anything>

### ISSUE THREAD

**Issue by jabbera** [dotnet/coreclr#10088]
I'm getting a crash during dotnet new (Unhandled exception at 0x00007FFC84107788 (KernelBase.dll) in dotnet.exe: 0xC0020001: The string binding is invalid (parameters: 0xFFFFFFFF8007042B)). Anecdotally turning off telemetry prevents the crash. I can supply a dump out of band if needed.

 with the following stack:

>	KernelBase.dll!RaiseException()	Unknown
 	coreclr.dll!TheUMEntryPrestubWorker(UMEntryThunk * pUMEntryThunk) Line 1157	C++
 	coreclr.dll!TheUMEntryPrestub() Line 80	Unknown
 	winhttp.dll!HTTP_USER_REQUEST::_IndicateInformational()	Unknown
 	winhttp.dll!HTTP_USER_REQUEST::OnSendingRequest()	Unknown
 	winhttp.dll!WEBIO_REQUEST::_OnInformation()	Unknown
 	webio.dll!WaIndicateHttpRequestInformation()	Unknown
 	webio.dll!WaSendHttpRequestOnConnection()	Unknown
 	webio.dll!WapHttpConnectCompletion()	Unknown
 	webio.dll!WapSslCompleteNegotiation()	Unknown
 	webio.dll!WaSslProcessReceiver()	Unknown
 	webio.dll!WapSslReceiveCompletionCallback()	Unknown
 	webio.dll!WapTcpReceiveCompletionRoutine()	Unknown
 	webio.dll!WapTpIoCompletionRoutine()	Unknown
 	KernelBase.dll!BasepTpIoCallback()	Unknown
 	ntdll.dll!TppIopExecuteCallback()	Unknown
 	ntdll.dll!TppWorkerThread()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

dotnet new --help

**Comment by gkhanna79** [comment]
@jabbera Can you please share specific repro steps, including details of which version of .NET Core SDK you were using?

**Comment by jabbera** [comment]
All I do is run: dotnet new --help

    C:\Users\mbarry>dotnet --version
    1.0.1

**Comment by gkhanna79** [comment]
@jabbera Are you able to repro this using the latest .NET Core (https://www.microsoft.com/net/download/core)?

**Comment by jabbera** [comment]
Looks good! Thanks!

**Comment by jabbera** [comment]
This is still an issue. The installer is saying 1.0.3 though:

![image](https://cloud.githubusercontent.com/assets/301208/25343470/2421e874-28dd-11e7-8c6d-891311347515.png)

**Comment by gkhanna79** [comment]
@rakeshsinghranchi @vivmishra I believe this is fixed for 1.0.5, right?

**Comment by rakeshsinghranchi** [comment]
Yes, UAC issue does not repro for 1.1.2 or 1.0.5. Testing was done against daily build from https://github.com/dotnet/core-setup .

**Comment by gkhanna79** [comment]
Thanks for the confirmation @rakeshsinghranchi. 

@jabbera do you have a repro of the crash with 1.0.4 that you can share?

**Comment by jabbera** [comment]
Still happening on just a dotnet new. I have a dump file if you want to provide and email address I can share it.

00000025`470fe460 00007ff9`bec90993 KERNELBASE!RaiseException+0x68
00000025`470fe540 00007ff9`bebec60e coreclr!WinMDInternalImportRO::Release+0x9ad83
00000025`470fe590 00007ff9`f8ea83b4 coreclr!TheUMEntryPrestub+0x3e
00000025`470fe600 00007ff9`f8ea6468 winhttp!HTTP_USER_REQUEST::_IndicateInformational+0xf0
00000025`470fe690 00007ff9`f8eb3def winhttp!HTTP_USER_REQUEST::OnSendingRequest+0x5a8
00000025`470fe9a0 00007ff9`ecb30053 winhttp!WEBIO_REQUEST::_OnInformation+0x15f
00000025`470fea60 00007ff9`ecb28dd7 webio!WaIndicateHttpRequestInformation+0x1c3
00000025`470fef50 00007ff9`ecb37582 webio!WaSendHttpRequestOnConnection+0x33
00000025`470fef90 00007ff9`ecb39f9e webio!WapHttpConnectCompletion+0x122
00000025`470ff040 00007ff9`ecb317c0 webio!WapSslCompleteNegotiation+0x14a
00000025`470ff090 00007ff9`ecb310fb webio!WaSslProcessReceiver+0x670
00000025`470ff150 00007ff9`ecb30f4d webio!WapSslReceiveCompletionCallback+0x6b
00000025`470ff1b0 00007ff9`ecb3f050 webio!WapTcpReceiveCompletionRoutine+0x17d
00000025`470ff230 00007ffa`0151e280 webio!WapTpIoCompletionRoutine+0x110
00000025`470ff2f0 00007ffa`0417f138 KERNELBASE!BasepTpIoCallback+0x50
00000025`470ff340 00007ffa`041836ad ntdll!TppIopExecuteCallback+0x118
00000025`470ff3c0 00007ffa`040a8364 ntdll!TppWorkerThread+0x8ed
00000025`470ff7c0 00007ffa`041b70d1 KERNEL32!BaseThreadInitThunk+0x14
00000025`470ff7f0 00000000`00000000 ntdll!RtlUserThreadStart+0x21

**Comment by gkhanna79** [comment]
What is the version of Windows?

**Comment by jabbera** [comment]
Windows 10 1607

**Comment by gkhanna79** [comment]
@ramarag PTAL

**Comment by ramarag** [comment]
@jabbera please provide the full repro steps. meanwhile can you share the crash dump on a file share ?

**Comment by jabbera** [comment]
@ramarag The repro is
'
set DOTNET_CLI_TELEMETRY_OPTOUT=0
dotnet new
' 
This crashes about every other time with the callstack above. Dump here: https://drive.google.com/file/d/0B9KmYWNS7tQ2ei0yT0ZnYkMzWWs/view?usp=sharing

**Comment by ramarag** [comment]
@jabbera can you share the cli you are using ? also can you try out the latest cli from https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-win-x64.latest.zip

From what i see, we are shutting down coreclr, when we unexpectedly get a callback due to IO completion from windows
