### ISSUE TITLE
[Regression] [x64 Windows] Test failure: System.Collections.Immutable.Tests.ImmutableListTest / IndexOf & LastIndexOf

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#16202]
_From @karelz on February 4, 2018 2:42_

## Type of failures

Affected OS: Win7 & Win8.1 & Win10 & Win10.Core & Win10.Nano - only x64 (x86 runs are fine)

```
Assert.Equal() Failure
Expected: 2
Actual:   -1

at System.Collections.Immutable.Tests.IndexOfTests.IndexOfTest[TCollection](Func`2 factory, Func`3 indexOfItem, Func`4 indexOfItemIndex, Func`5 indexOfItemIndexCount, Func`6 indexOfItemIndexCountEQ) in E:\A\_work\484\s\corefx\src\System.Collections.Immutable\tests\IndexOfTests.cs:line 45
at System.Collections.Immutable.Tests.ImmutableListTest.IndexOf() in E:\A\_work\484\s\corefx\src\System.Collections.Immutable\tests\ImmutableListTest.cs:line 505
```

## History of failures

Day | Build | Details
-- | -- | --
2/3 | 20180203.03 | 10x failures - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180203.03/workItem/System.Collections.Immutable.Tests)
2/4 | 20180204.01 | 10x failures - [link](https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180204.01/workItem/System.Collections.Immutable.Tests)

_Copied from original issue: dotnet/corefx#26821_

**Comment by jkotas** [comment]
_From @karelz on February 4, 2018 2:42_

@safern @ianhays can you please take a look?

**Comment by jkotas** [comment]
@dotnet/jit-contrib This looks like a silent bad codegen bug.

**Comment by AndyAyersMS** [comment]
Do we know how recently this regressed? I can look into this if nobody else has gotten into it yet.

**Comment by jkotas** [comment]
It works fine on live master. I think it was fixed by https://github.com/dotnet/coreclr/pull/16218

**Comment by Sunny-pu** [comment]
failed again in CI:
https://ci.dot.net/job/dotnet_corefx/job/master/job/outerloop_netcoreapp_win7_release/393/testReport/System.Collections.Immutable.Tests/ImmutableListTest/LastIndexOf/

**Comment by safern** [comment]
That build didn't have #16218 yet, the build was 12 hours ago and this was merged 10 hours ago + it has to be consumed in corefx so that the tests run against the fix. So I guess we should keep an eye on tomorrow's build and see if we can close the issue.

**Comment by joshfree** [comment]
This is still failing in the rolling runs https://mc.dot.net/#/product/netcore/master/source/official~2Fcorefx~2Fmaster~2F/type/test~2Ffunctional~2Fcli~2F/build/20180208.06/workItem/System.Collections.Immutable.Tests/analysis/xunit/System.Collections.Immutable.Tests.ImmutableListTest~2FIndexOf

**Comment by AndyAyersMS** [comment]
Ok, I'll investigate.

**Comment by AndyAyersMS** [comment]
Looks like this started failing with c4943e0  (#15910) which we reverted at #16218.

Trying to check if rolling runs have seen the reversion yet....

**Comment by AndyAyersMS** [comment]
I don't believe they have seen it yet. Let's wait and see if the next CoreCLR update to CoreFX fixes this.

**Comment by AndyAyersMS** [comment]
Fixed if I drop in the latest jit... so it should correct itself once CoreCLR bits propagate.

**Comment by AndyAyersMS** [comment]
Looks like the bits have finally propagated and the test is once again passing.
